leftnav:
- identifier: 04926453-2a3f-f348-fbfa-2399ff7c1348
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: external-9ff6034b7cb54a64a2775c3a3eb2b50c
  name: Online Publication
  url: http://introtodeeplearning.com/2020/index.html
  weight: 1000
